#!/usr/bin/expect -f

set timeout -1

set workdir [lindex $argv 0];

spawn $workdir/liteclient-build/lite-client/lite-client -C $workdir/liteclient-build/ton-lite-client-test1.config.json
sleep 1
expect ""
send -- "last\r"
sleep 1
send \x03
expect eof