#!/usr/bin/expect -f

set timeout -1

set workdir [lindex $argv 0];
set userid [lindex $argv 1];
set senderpub [lindex $argv 2];
set destpub [lindex $argv 3];
set network [lindex $argv 4];

spawn $workdir/liteclient-build/lite-client/lite-client -C $workdir/liteclient-build/ton-lite-client-test1.config.json
sleep 1
expect ""
send -- "sendfile $workdir/$network/$userid/send-$senderpub-$destpub.boc\r"
sleep 1
send \x03
expect eof